<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<title></title>
<link href="css/css.php" rel="stylesheet" type="text/css" />
<script src="js/js.php" type="text/javascript"></script>
</head>
<body>
<form action="" method="post" id="formOneManga">
  <fieldset>
    <legend>OneManga Web Downloader - Search</legend>
    <ol>
      <li>
        <label for="manganame">Manga Keyword: <em>required</em></label>
        <input size="20" id="manganame" name="manganame" class="required" type="text" value="" />
      </li>
    </ol>
  </fieldset>
  <fieldset class="submit">
    <input name="submit" type="submit" value="Submit" />
    <input type="reset" name="Reset" id="button" value="Reset" />
  </fieldset>
  <script type="text/javascript">new Validation('formOneManga');</script>
</form>
<p><br />
  <a href="http://validator.w3.org/check?uri=referer"><img src="images/valid-xhtml10-blue.png" alt="Valid XHTML 1.0 Strict" height="31" width="88" /></a> </p>
</body>
</html>
